- name: Upgrade all packages to the latest version
  hosts: all
  become: yes
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
       name: "*"
       state: latest  
      
