- name: install packages on a fresh Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install all packages
      apt: 
        pkg: 
        - vlc
        - audacity
        - inkscape
        - aptitude
      
    - name: Upgrade all packages to the latest version
      apt:
       name: "*"
       state: latest  
