- name: install packages on a fresh Ubuntu
  hosts: all
   
  tasks:
    - name: install all packages
      apt: name: ['vlc', 'audacity'] state=present
      become: yes
      become_method: su
      
