- name: install packages on a fresh Ubuntu
  hosts: all
   
  tasks:
    - name: install all packages
      apt: 
        pkg: 
        - vlc
        - audacity
      become: yes
      become_method: su
     
